name: Documentation Issue
description: Report an issue with documentation
title: "[Docs]: "
labels: ["documentation", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve our documentation!

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please confirm the following before submitting
      options:
        - label: I have searched existing issues and this is not a duplicate
          required: true

  - type: dropdown
    id: doc_type
    attributes:
      label: Documentation Type
      description: What type of documentation needs improvement?
      options:
        - Resource Documentation
        - Data Source Documentation
        - Provider Configuration
        - Guide/Tutorial
        - Example Configuration
        - README
        - Other
    validations:
      required: true

  - type: input
    id: doc_location
    attributes:
      label: Documentation Location
      description: Where is the documentation located?
      placeholder: "e.g., docs/resources/certificate.md, README.md, examples/resources/certificate/"
    validations:
      required: true

  - type: dropdown
    id: issue_type
    attributes:
      label: Issue Type
      description: What's wrong with the documentation?
      options:
        - Outdated Information
        - Incorrect Information
        - Missing Information
        - Unclear/Confusing
        - Typo/Grammar
        - Broken Link
        - Missing Example
        - Other
    validations:
      required: true

  - type: textarea
    id: current_content
    attributes:
      label: Current Content
      description: What does the documentation currently say? (copy/paste the relevant section)
      placeholder: "Current documentation states..."
    validations:
      required: true

  - type: textarea
    id: issue_description
    attributes:
      label: Issue Description
      description: What's wrong with the current content?
      placeholder: |
        The documentation states X, but it should say Y because...
    validations:
      required: true

  - type: textarea
    id: suggested_improvement
    attributes:
      label: Suggested Improvement
      description: How should the documentation be improved?
      placeholder: |
        The documentation should instead say...

        Or add the following example:
        ```hcl
        resource "cyberarksia_example" "demo" {
          # ...
        }
        ```
    validations:
      required: true

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Add any other context or screenshots
      placeholder: "Additional details..."
    validations:
      required: false
